version: '2'
services:
    jhip201802-app:
        image: jhip201802
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhip201802-mysql:3306/jhip201802?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhip201802-mysql:
        extends:
            file: mysql.yml
            service: jhip201802-mysql
